# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:


    encoders:
        #1Symfony\Component\Security\Core\User\User: plaintext
        #2OC\UserBundle\Entity\User: plaintext
        #OC\UserBundle\Entity\User: sha512
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    #providers:
    #    main:
    #        id: fos_user.user_provider.username
    providers:
       fos_userbundle:
                   id: fos_user.user_provider.username
        #2main:
        #2    entity:
        #2        class: OC\UserBundle\Entity\User
        #2        property: username
        #1in_memory:
        #1    memory:
        #1        users:
        #1            auteur: { password: auteurpass, roles: [ 'ROLE_AUTEUR' ] }
        #1            user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #1            admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        #1main_login:
        #1    pattern: ^/login$
        #1    anonymous: true
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/s-api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /s-api/login_check
                username_parameter: username
                password_parameter: password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/s-api
            stateless: true
            provider: fos_userbundle
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            anonymous: ~
        #main:
        #    pattern:   ^/
        #    anonymous: true
        #    provider:  main
        #    #1anonymous: false
        #    form_login:
        #        login_path: fos_user_security_login
        #        check_path: fos_user_security_check
        #    logout:
        #        path:       fos_user_security_logout
        #        target:     fos_user_security_login
        #    remember_me:
        #        secret: %secret%
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/s-api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/s-api,       roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/admin, ip: 127.0.0.1, requires_channel: https }
