security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        oc_provider:
            id: oc_demo_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:   ^/demo/secured/login$
            security: false

        secured_area:
            pattern:   ^/demo/secured/
            webservice-login:
                login_path: /demo/secured/login
                check_path: /demo/secured/login_check
                provider: oc_provider
            logout:
                path:       /demo/secured/logout
                target:     /demo/
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/admin, ip: 127.0.0.1, requires_channel: https }
